from enum import Enum


class FAVORITE_REGION(Enum):
    CRIME_ALLEY = "CRIME_ALLEY"
    AKRHAM_ASYLUM = "ARKHAM_ASYLUM"
    OLD_GOTHAM = "OLD_GOTHAM"
    GOTHAM_COUNTRY_UNDERWATER_TUBES = "GOTHAM_COUNTRY_UNDERWATER_TUBES"
    ROBBINSVILLE = "ROBBINSVILLE"
    CITY_HALL = "CITY_HALL"
    WAYNE_TOWER = "WAYNE_TOWER"
    GRANT_PARK = "GRANT_PARK"
