from enum import Enum


class TYPE_CRIME(Enum):
    MURDER = "MURDER"
    SEXUAL_ASSAULT = "SEXUAL_ASSAULT"
    THEFT = "THEFT"
    DOMESTIC_VIOLENCE = "DOMESTIC_VIOLENCE"
    CRIME_AGAINST_SELFAS_THE_BEST_PROJECT = "CRIME_AGAINST_SELFAS_THE_BEST_PROJECT"
    NAZI = "NAZI"
    HATER_OF_INTERESTELLAR = "HATER_OF_INTERESTELLAR"
    FUCK_BOY = "FUCK_BOY"
